name: Apply Branch Protection Rules

on:
  push:
    branches:
      - main

jobs:
  apply-branch-protection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Ensure a recent version of Node.js is used

      - name: Install dependencies
        run: npm install @octokit/rest

      - name: Apply branch protection rules
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node .github/scripts/apply-branch-protection.js
