name: Apply Branch Protection Rules

on:
  push:
    branches:
      - main

permissions:
  contents: write
  administration: write

jobs:
  apply-branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Set up branch protection rules
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.ENV_GITHUB_PAT }}
          script: |
            const { context, GitHub } = require('@actions/github');

            const repo = context.repo;
            const branch = 'main';
            const octokit = new GitHub(process.env.ENV_GITHUB_PAT);

            octokit.repos.updateBranchProtection({
              ...repo,
              branch: branch,
              required_status_checks: {
                strict: true,
                contexts: ["Spectral Check"]
              },
              enforce_admins: true,
              required_pull_request_reviews: {
                dismissal_restrictions: {},
                dismiss_stale_reviews: true,
                require_code_owner_reviews: true,
                required_approving_review_count: 1
              },
              restrictions: null,
              allow_force_pushes: false,
              allow_deletions: false
            });
