name: Apply Branch Protection Rules

on:
  push:
    branches:
      - main

permissions:
  contents: write
  administration: write

jobs:
  apply-branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Set up branch protection rules
        env:
          GITHUB_PAT: ${{ secrets.ENV_GITHUB_PAT }}
        run: |
          curl -X PUT -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $ENV_GITHUB_PAT" \
            https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/branches/main/protection \
            -d '{
              "required_status_checks": {
                "strict": true,
                "contexts": ["Spectral Check"]
              },
              "enforce_admins": true,
              "required_pull_request_reviews": {
                "dismissal_restrictions": {},
                "dismiss_stale_reviews": true,
                "require_code_owner_reviews": true,
                "required_approving_review_count": 1
              },
              "restrictions": null,
              "allow_force_pushes": false,
              "allow_deletions": false
            }'
